### ISSUE TITLE
So, how _do_ I generate a default conf file?

### ISSUE THREAD

**Issue by rlipscombe** [basho/cuttlefish#154]
The wiki talks about generating default config files, but doesn't say how to actually do this.

**Comment by rlipscombe** [comment]
Oh, OK. It's done by the rebar plugin.

But we don't use "rebar generate" -- we're using relx. We could write a relx plugin for cuttlefish, but until then:

```
{_, Mappings, _} = cuttlefish_schema:files(filelib:wildcard("path/to/*.schema")).
ok = cuttlefish_conf:generate_file(Mappings, "path/to/generated.conf").
```

**Comment by joedevivo** [comment]
Yeah, that's how. I'll add it to the documentation.
