### ISSUE TITLE
Parameterize the duration type

### ISSUE THREAD

**Issue by seancribbs** [basho/cuttlefish#24]
There are several cases where durations need to be expressed in magnitudes other than milliseconds. There already exists a `duration_secs` type but it would be much simpler (requiring fewer translations in the schema) if the type were parameterized by the desired magnitude, e.g.

``` erlang
{datatype, {duration, minutes}}
% or
{datatype, {duration, seconds}}
```

**Comment by joedevivo** [comment]
Fixed in #25
