### ISSUE TITLE
storage_backend value not checked

### ISSUE THREAD

**Issue by vinoski** [basho/cuttlefish#31]
Setting `storage_backend` to "eleveldb" instead of "leveldb" is an error, but it's silently ignored. This was seen using [cuttlefish commit 09a1aa93](https://github.com/basho/cuttlefish/commit/09a1aa933757b8aa0f4956dbf4361c863353df77), but might also be an issue with previous versions as well.

**Comment by joedevivo** [comment]
I'm thinking that maybe for enums, we default to 'undefined' if you choose a value not supported. which it better than seeing 'eleveldb' and saying "I don't know what that is, so default to bitcask"
