### ISSUE TITLE
Make sure generated files are somewhere writable by packaging rules

### ISSUE THREAD

**Issue by jonmeredith** [basho/cuttlefish#32]
Running pre1 I noticed this in the log output.

```
-config /Users/jmeredith/basho/work/riak-security/rel/riak/bin/../etc/generated/app.2013.09.18.17.58.25.config -args_file /Users/jmeredith/basho/work/riak-security/rel/riak/bin/../etc/generated/vm.2013.09.18.17.58.25.args
```

the etc directory isn't guaranteed to be writable by the node.  Generated tmp files need to be written somewhere the application has permissions according to os-specific packaging rules.

**Comment by joedevivo** [comment]
Fixed in above referenced PRs
