### ISSUE TITLE
Error generating config with cuttlefish, there should be logs

### ISSUE THREAD

**Issue by reiddraper** [basho/cuttlefish#51]
There are no logs. `file:consult/` on the advanced.config works fine. Not sure what's up.

**Comment by reiddraper** [comment]
[Here's](https://gist.github.com/reiddraper/e44b72a1bb6658bf3a30) the `riak.conf` I'm using. It was generated by riak_test.

**Comment by joedevivo** [comment]
@reiddraper also mentioned that he was using an advanced.config as well. It can be found [here](https://gist.github.com/reiddraper/1c0bcfddb9b61b1a6bd8)

**Comment by joedevivo** [comment]
I'll be adding a PR to node package that removed the "there should be logs" message. Those logs should have been output to stderr. If they weren't I don't want people thinking they should be somewhere.

**Comment by reiddraper** [comment]
Cool. Do these configs let you start Riak? Any idea what the issue might be?

**Comment by joedevivo** [comment]
This turned out to be an issue with riak_test, in which a global gitignore file prevented the cluster under test from being reinitialized.
