### ISSUE TITLE
fsm_limit has unexpected behavior

### ISSUE THREAD

**Issue by evanmcc** [basho/cuttlefish#56]
fsm_limit has two valid value types: 
an integer, or the atom undefined

undefined has the special meaning of disabling the sidejob subsystem entirely, which we now can't do.

**Comment by joedevivo** [comment]
How would you feel about splitting that into two different settings?

**Comment by evanmcc** [comment]
Wfm, just didn't know how to make it happen either way.

**Comment by joedevivo** [comment]
The ability was added in #89.
