### ISSUE TITLE
How to handle 'redefined' variables

### ISSUE THREAD

**Issue by Licenser** [basho/cuttlefish#68]
So this is a bit related to #67, when having some variable shadowing it should be possible in what way it does so. I can see two scenarios:
# totally replace the variable

When I define my.setting before  (with a higher priority) and use translate or alias to `riak_core.something` then the `riak_core.something` from `riak_core.schema` will never show in the config and even if added be simply ignore (or a warning printed that it's a unknown setting)
# defaulting/simplification

Example take the code in #67  for example, there the `data_dir` in there would be a default for `bitcask.data_dir` etc. So it would be neat if `bitcask.data_dir`, would not be present in the generated `.config`, but if added explictly would overwrite the 'default' provided by `data_dir`

**Comment by joedevivo** [comment]
Did you mean 67 instead of 64 in that last paragraph?

**Comment by Licenser** [comment]
totally, updated the orignial message.

**Comment by joedevivo** [comment]
It was built with the "totally replace" semantic in mind. That's why the alphanumeric order of the schema file names is so inmportant in reltool.config.

The idea being that if you want to include the bitcask schema, but want to override a specific setting, you could include that one mapping in your own app's schema.

**Comment by joedevivo** [comment]
Hey @Licenser, I just added the ability to partially overwrite mappings. Take a look at #78

**Comment by Licenser** [comment]
looks neat!

**Comment by joedevivo** [comment]
closing this issue, the merge property for mappings covers this. correct me if that's wrong.
