### ISSUE TITLE
Priority order seems to be the wrong way around

### ISSUE THREAD

**Issue by Licenser** [basho/cuttlefish#70]
in my tests a 01- file overwrites a 00- file and a 99- one overwrites a 01- one.

**Comment by Licenser** [comment]
To make this more interesting:

## 00.schema
- define setting_form_01 as setting_form_00 (to overwrite it)

## 01.schema
- define settingr_form_01 as setting_form_01

## 99.schema (its the same as 00)
- define setting_form_01 as setting_form_00 (to overwrite it)

Generate config it looks like:

```
setting_form_00 = bla
setting_form_01 = blubb
```

The expected value from setting_form_01 would be `bla` since setting_form_00 should over write it. Sad story, it's `blubber`.

More experiment!

Remove 00.schema (but leave the generated config). Outcome is `bla` what why?

Regenerating the config with only 01 and 99 reverses the order so it makes it look like:

```
setting_form_01 = blubb
setting_form_00 = bla
```

**Comment by joedevivo** [comment]
covered in #73, closing
